import type { ColumnType, FilterOperator, JoinOperator } from "@/types"
import {
  ArrowDownIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CheckCircledIcon,
  CircleIcon,
  CrossCircledIcon,
  QuestionMarkCircledIcon,
  StopwatchIcon,
  TableIcon,
  ViewHorizontalIcon,
  ViewVerticalIcon,
} from "@radix-ui/react-icons"
import {
  Filter,
  Download,
  ListChecks,
  Pencil,
} from "lucide-react"

export const dataTableConfig = {
  columnTypes: [
    "text",
    "number",
    "date",
    "boolean",
    "select",
    "multi-select",
  ] as const,
  globalOperators: [
    "equals",
    "not-equals",
    "greater-than",
    "greater-than-or-equals",
    "less-than",
    "less-than-or-equals",
    "contains",
    "not-contains",
    "starts-with",
    "ends-with",
    "is-empty",
    "is-not-empty",
  ] as const,
  textOperators: [
    "contains",
    "not-contains",
    "equals",
    "not-equals",
    "starts-with",
    "ends-with",
    "is-empty",
    "is-not-empty",
  ] as const,
  numberOperators: [
    "equals",
    "not-equals",
    "greater-than",
    "greater-than-or-equals",
    "less-than",
    "less-than-or-equals",
    "is-empty",
    "is-not-empty",
  ] as const,
  dateOperators: [
    "equals",
    "not-equals",
    "greater-than",
    "greater-than-or-equals",
    "less-than",
    "less-than-or-equals",
    "is-empty",
    "is-not-empty",
  ] as const,
  selectOperators: [
    "equals",
    "not-equals",
    "is-empty",
    "is-not-empty",
  ] as const,
  filterOperators: {
    equals: "Igual a",
    "not-equals": "Diferente de",
    "greater-than": "Maior que",
    "greater-than-or-equals": "Maior ou igual a",
    "less-than": "Menor que",
    "less-than-or-equals": "Menor ou igual a",
    contains: "Contém",
    "not-contains": "Não contém",
    "starts-with": "Começa com",
    "ends-with": "Termina com",
    "is-empty": "Está vazio",
    "is-not-empty": "Não está vazio",
  },
  joinOperators: [
    { label: "E", value: "and" },
    { label: "Ou", value: "or" },
  ] as const,
  sortOrders: [
    { label: "Crescente", value: "asc" },
    { label: "Decrescente", value: "desc" },
  ] as const,
  featureFlags: [
    {
      label: "Tabela Avançada",
      value: "advancedTable",
      icon: TableIcon,
      tooltipTitle: "Tabela Avançada",
      tooltipDescription: "Habilita recursos avançados da tabela como filtros complexos e visualizações customizadas",
      dependencies: [],
    },
    {
      label: "Barra Flutuante",
      value: "floatingBar",
      icon: ViewHorizontalIcon,
      tooltipTitle: "Barra Flutuante",
      tooltipDescription: "Exibe uma barra flutuante com ações quando itens são selecionados",
      dependencies: ["advancedTable"],
    },
    {
      label: "Customização de Colunas",
      value: "columnCustomization",
      icon: ViewVerticalIcon,
      tooltipTitle: "Customização de Colunas",
      tooltipDescription: "Permite reordenar, redimensionar e ocultar colunas",
      dependencies: [],
    },
    {
      label: "Filtros Avançados",
      value: "advancedFilters",
      icon: Filter,
      tooltipTitle: "Filtros Avançados",
      tooltipDescription: "Habilita filtros avançados com operadores lógicos e condições complexas",
      dependencies: ["advancedTable"],
    },
    {
      label: "Exportação",
      value: "dataExport",
      icon: Download,
      tooltipTitle: "Exportação de Dados",
      tooltipDescription: "Permite exportar dados da tabela em diferentes formatos",
      dependencies: [],
    },
    {
      label: "Ações em Lote",
      value: "bulkActions",
      icon: ListChecks,
      tooltipTitle: "Ações em Lote",
      tooltipDescription: "Permite executar ações em múltiplos itens selecionados",
      dependencies: ["floatingBar"],
    },
    {
      label: "Ações por Linha",
      value: "rowActions",
      icon: ArrowRightIcon,
      tooltipTitle: "Ações por Linha",
      tooltipDescription: "Adiciona menu de ações para cada linha da tabela",
      dependencies: [],
    },
    {
      label: "Edição Inline",
      value: "inlineEditing",
      icon: Pencil,
      tooltipTitle: "Edição Inline",
      tooltipDescription: "Permite editar dados diretamente na tabela",
      dependencies: ["advancedTable"],
    },
  ] as const,
  priorities: [
    {
      label: "Baixa",
      value: "low",
      icon: ArrowDownIcon,
    },
    {
      label: "Média",
      value: "medium",
      icon: ArrowRightIcon,
    },
    {
      label: "Alta",
      value: "high",
      icon: ArrowUpIcon,
    },
  ],
  statuses: [
    {
      label: "Backlog",
      value: "backlog",
      icon: QuestionMarkCircledIcon,
    },
    {
      label: "Todo",
      value: "todo",
      icon: CircleIcon,
    },
    {
      label: "Em Progresso",
      value: "in_progress",
      icon: StopwatchIcon,
    },
    {
      label: "Concluído",
      value: "done",
      icon: CheckCircledIcon,
    },
    {
      label: "Cancelado",
      value: "canceled",
      icon: CrossCircledIcon,
    },
  ],
} as const

export type DataTableConfig = typeof dataTableConfig
